In [3]:
import numpy as np

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(2)

array([0.90002631, 0.87301169])

In [23]:
np.random.rand(5,5)

array([[0.14021295, 0.54623833, 0.82873011, 0.81892624, 0.34162326],
       [0.30469921, 0.75824929, 0.71398107, 0.14794102, 0.18558521],
       [0.4729225 , 0.65373082, 0.14939422, 0.56379954, 0.99810828],
       [0.20219612, 0.13275574, 0.46929789, 0.68871325, 0.18215773],
       [0.7827942 , 0.35144024, 0.6721451 , 0.0179359 , 0.40695014]])

In [24]:
np.random.randn(2)

array([ 0.60947808, -0.00734947])

In [25]:
np.random.randn(5,5)

array([[ 1.1279329 ,  1.51987883, -0.06028237, -0.58193097,  0.56420829],
       [ 0.44506037, -0.44487314,  0.18422803,  0.70040881, -0.49756977],
       [ 1.55773856, -1.78783622,  1.02592179,  0.42665065,  0.80262595],
       [-0.61974779,  0.71008019,  0.31047234, -0.50537989, -0.43032637],
       [ 1.46126635, -1.25110927, -0.640986  , -0.53009108, -2.23500984]])

In [26]:
np.random.randint(1,100)

71

In [27]:
np.random.randint(1,100,10)

array([37, 12, 53, 86, 67,  9, 99, 50, 68, 31])

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([15,  5,  8, 14, 32, 42, 34, 35, 46, 15])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([15,  5,  8, 14, 32, 42, 34, 35, 46, 15])

In [34]:
ranarr.max()

46

In [35]:
ranarr.argmax()

8

In [36]:
ranarr.min()

5

In [37]:
ranarr.argmin()

1

In [38]:
# Vector
arr.shape

(25,)

In [39]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [41]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [42]:
arr.reshape(25,1).shape

(25, 1)

In [43]:
arr.dtype

dtype('int32')