In [1]:
import numpy as np

In [2]:
# Create sample array
arr = np.arange(0,11)

In [3]:
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Get a value at an index
arr[8]

8

In [5]:
# get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
# Setting a value with index range (Broadcasting)
arr[0:5]=100

# Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Reset array, we'll see why I had to reset in a moment
arr = np.arange(0,11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Important notes on Slices
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
# Change Slice
slice_of_arr[:]=99

# Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
# To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Show

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [18]:
# Format is arr_2d[row][col] ar arr_2d[row, col]

# Getting individual element value
arr_2d[1][0]

20

In [19]:
# Getting individual element value
arr_2d[1,0]

20

In [20]:
# 2D array slicing

# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
# Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [23]:
# Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [24]:
# Set up matrix
arr2d = np.zeros((10, 10))

In [25]:
# Length of array
arr_length = arr2d.shape[1]

In [26]:
# Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [27]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [28]:
# allow in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [30]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
bool_arr = arr > 4

In [33]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])